spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
quiz:
  app:
    app-name: QuizMaster-Dev
    max-questions: 50
    feature-enabled: true
server:
  port: 8443
logging:
  level:
    org.springframework: DEBUG
    ge.tsu.Quiz: DEBUG
---
#spring:
#  profiles: prod
#quiz:
#  app:
#    app-name: QuizMaster-Prod
#    max-questions: 20
#    feature-enabled: false
#server:
#  port: 8443
#logging:
#  level:
#    org.springframework: INFO
#    ge.tsu.Quiz: INFO